# Generated by Django 2.2.5 on 2019-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('desc', models.TextField(blank=True, max_length=256)),
                ('date', models.DateField()),
            ],
        ),
    ]
