# Generated by Django 2.2.5 on 2019-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdbook', '0002_auto_20190929_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
