# Generated by Django 2.2.6 on 2019-11-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdbook', '0004_auto_20191101_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='bdbook.Book')),
            ],
        ),
    ]
