# Generated by Django 2.2.6 on 2019-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdbook', '0005_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Book', models.ManyToManyField(related_name='authors', to='bdbook.Book')),
            ],
        ),
    ]
